<?php

namespace App\Controller;

use App\Model\SaleUserModel;

class SalesUser extends Sales
{
    protected string $tableName = "sale";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new SaleUserModel($config);
        $this->model->setUserId($_SESSION['user']['id']);

    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData([
                "groupList1" => $this->model->getGroupListUsers(),
                "groupList2" => $this->model->getGroupListCountries(),
                "groupList3" => $this->model->getGroupListProdukt(),
                "groupList4" => $this->model->getGroupListCustomers()
            ])
            ->setTemplate("SalesUser/add_edit");
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData([
                "groupList1" => $this->model->getGroupListUsers(),
                "groupList2" => $this->model->getGroupListCountries(),
                "groupList3" => $this->model->getGroupListProdukt(),
                "groupList4" => $this->model->getGroupListCustomers()
            ])
            ->setTemplate("SalesUser/add_edit");
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub

        $this->view->setTemplate("SalesUser/show");
    }
    public function actionAdd(): void
    {
        $_POST['users_id']=$_SESSION['user']['id'];
        parent::actionAdd(); // TODO: Change the autogenerated stub
    }
}