<?php

namespace App\Controller;

use App\Model\SalesModel;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlxs;

class Sales extends Table
{
    protected string $tableName = "sale";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new SalesModel($config);

    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData([
                "groupList1" => $this->model->getGroupListUsers(),
                "groupList2" => $this->model->getGroupListCountries(),
                "groupList3" => $this->model->getGroupListProdukt(),
                "groupList4" => $this->model->getGroupListCustomers()
            ])
            ->setTemplate("Sales/add_edit");
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData([
                "groupList1" => $this->model->getGroupListUsers(),
                "groupList2" => $this->model->getGroupListCountries(),
                "groupList3" => $this->model->getGroupListProdukt(),
                "groupList4" => $this->model->getGroupListCustomers()
            ])
            ->setTemplate("Sales/add_edit");
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Sales/show");
    }

    public function actionAdd(): void
    {
        parent::actionAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Sales/add_edit");
    }

    public function spreadsheet_format_download()
    {
        header('Content-Type:application/vnd.ms-excel');
        header('Content-Disposition: attachment; filename="Hello_world.xlsx"');
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue('A1', 'data');
        $sheet->setCellValue('B1', 'Предприятие');
        $sheet->setCellValue('C1', 'Покупатель');
        $sheet->setCellValue('D1', 'Страна');
        $sheet->setCellValue('E1', 'Продукция');
        $sheet->setCellValue('F1', 'Вес, тонн');
        $sheet->setCellValue('G1', 'Стоимость, тыс.долл.');
        $writer = new Xlsx($spreadsheet);
        $writer = save("php//output");
    }
    public function spreadsheet_export()
    {
        header('Content-Type:application/vnd.ms-excel');
        header('Content-Disposition: attachment; filename="Hello_world.xlsx"');
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue('A1', 'data');
        $sheet->setCellValue('B1', 'gредприятие');
        $sheet->setCellValue('C1', 'Покупатель');
        $sheet->setCellValue('D1', 'Страна');
        $sheet->setCellValue('E1', 'Продукция');
        $sheet->setCellValue('F1', 'Вес, тонн');
        $sheet->setCellValue('G1', 'Стоимость, тыс.долл.');
//        $count=2;
//        foreach ($this->data["comments"] as $row) {
//
//            $oSpreadsheet_Out->setActiveSheetIndex(0)
//                ->setCellValue('A' . $count, $row['data']);
//            ->setCellValue('B1', 'Предприятие')
//            ->setCellValue('C1', 'Покупатель')
//            ->setCellValue('D1', 'Страна')
//            ->setCellValue('E1', 'Продукция')
//            ->setCellValue('F1', 'Вес, тонн')
//            ->setCellValue('G1', 'Стоимость, тыс.долл.')
//        $count++;
//        }
        $writer = new Xlsx($spreadsheet);
        $writer = save("php//output");
    }


}